Bookcase/Controllers/RateController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bookcase.ViewModels;
using BookcaseData.DAL;
using BookcaseData.EntityModels;
using BookcaseData.Repositories;
using PagedList;

namespace Bookcase.Controllers
{
    public class RateController : Controller
    {
        private readonly IRateRepository _rateRepository;
        private readonly IPersonRepository _personRepository;
        private readonly IBookRepository _bookRepository;

        public RateController()
        {
            this._rateRepository = new RateRepository(new BookcaseContext());
            this._personRepository = new PersonRepository(new BookcaseContext());
            this._bookRepository = new BookRepository(new BookcaseContext());
        }

        // GET: Rate
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "nameDescending" : "";
            ViewBag.WriterSortParm = sortOrder == "Writer" ? "writerDescending" : "Writer";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var allrates = _rateRepository.GetAll();

            if (!string.IsNullOrEmpty(searchString))
            {
                allrates = allrates.Where(s => s.BookId.ToString().ToLower().Contains(searchString) || s.PersonId.ToString().ToLower().Contains(searchString));

            }

            switch (sortOrder)
            {
                case "nameDescending":
                    allrates = allrates.OrderByDescending(b => b.Id);
                    break;
                case "Writer":
                    allrates = allrates.OrderBy(b => b.BookId);
                    break;
                case "writerDescending":
                    allrates = allrates.OrderByDescending(b => b.BookId);
                    break;
                default:
                    allrates = allrates.OrderBy(b => b.Id);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            List<RateVM> rateVms = new List<RateVM>();
            foreach (var rate in allrates)
            {
                rateVms.Add(MapToVm(rate));
            }

            return View(rateVms.ToPagedList(pageNumber, pageSize));
        }

        private static RateVM MapToVm(Rate rate)
        {
            return new RateVM
            {
                Rating = rate.Rating,
                BookId = rate.BookId,
                PersonId = rate.PersonId,
                Id = rate.Id,
                PersonName = rate.Person.Fullname,
                BookName = rate.Book.Title
            };
        }

        private static void MapFromVm(RateVM vm, Rate entity)
        {
            entity.Rating = vm.Rating;
            entity.BookId = vm.BookId;
            entity.PersonId = vm.PersonId;
            entity.Id = vm.Id;
        }

        //GET
        public ActionResult AddRate()
        {
            var rateVm = new RateVM();
            SetUsersSelectList(rateVm);
            SetBooksSelectList(rateVm);

            return View("AddRate", rateVm);
        }

        private void SetUsersSelectList(RateVM vm)
        {
            vm.UsersSelectList = _personRepository.GetAll().Select(x => new SelectListItem() { Text = x.Fullname, Value = x.Id.ToString() }).ToList();
        }
        private void SetBooksSelectList(RateVM vm)
        {
            vm.BooksSelectList = _bookRepository.GetAll().Select(x => new SelectListItem() { Text = x.Title, Value = x.Id.ToString() }).ToList();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddRate(RateVM rateVm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var rate = new Rate();
                    MapFromVm(rateVm, rate);
                    _rateRepository.Add(rate);
                    _rateRepository.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Wystąpił błąd zapisu, spróbuj ponownie");
            }
            return View(rateVm);
        }

        //GET
        public ActionResult UpdateRate(int id)
        {

            var rate = _rateRepository.GetById(id);
            if (rate == null)
            {
                return HttpNotFound();
            }
            return View(MapToVm(rate));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateRate(RateVM rateVm)
        {
            if (rateVm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                var rate = _rateRepository.GetById(rateVm.Id);
                MapFromVm(rateVm, rate);
                _rateRepository.Update(rate);

                try
                {
                    _rateRepository.Save();
                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Wystąpił błąd zapisu, spróbuj ponownie");
                }
            }
            return View(rateVm);
        }

        //GET
        public ActionResult DeleteRate(int id, bool? saveChanges = false)
        {
            if (saveChanges.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Błąd podczas usuwania, spróbuj ponownie";
            }
            var rate = _rateRepository.GetById(id);

            if (rate == null)
            {
                return HttpNotFound();
            }
            return View(MapToVm(rate));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRate(int id)
        {
            try
            {
                _rateRepository.Delete(id);
                _rateRepository.Save();

            }
            catch (RetryLimitExceededException)
            {
                return RedirectToAction("DeleteRate", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }
    }
}

Bookcase/Views/Rate/AddRate.cshtml
@model Bookcase.ViewModels.RateVM
@{
    ViewBag.Title = "AddRate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodaj Ocenę</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BookId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.BookId, Model.BooksSelectList, "Wybierz")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.PersonId, Model.UsersSelectList, "Wybierz")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cofnij do listy", "Index")
</div>

Bookcase/Views/Rate/DeleteRate.cshtml
@model Bookcase.ViewModels.RateVM
@{
    ViewBag.Title = "DeleteRate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Usuń ocenę</h2>

<h3>Na pewno?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróć do listy", "Index")
        </div>
    }
</div>

Bookcase/Views/Rate/Index.cshtml
@model PagedList.IPagedList<Bookcase.ViewModels.RateVM>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Oceny</h2>

@Html.ActionLink("Dodaj Ocenę", "AddRate", "Rate")
<br />
<br />
@using (Html.BeginForm("Index", "Rate", FormMethod.Get))
{
    <p>
        Szukaj: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Szukaj" />
    </p>
}
<br />
<table style="width: 50%" border-collapse collapse>
    <tr>
        <th>
            @Html.ActionLink("ID ", "Index", new { SortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Tytuł Książki", "Index", new {SortOrder = ViewBag.WriterSortParm, currentFilter = ViewBag.CurrentFilter})
        </th>
        <th>
            Wypożyczający
        </th>
        <th>
            Ocena
        </th>
        <th></th>

    </tr>
    @foreach (var item in Model)
    {
        <tr> <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PersonName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>

            <td>
                @Html.ActionLink("Edit", "UpdateRate", new { id = item.Id })
                @Html.ActionLink("Delete", "DeleteRate", new { id = item.Id })
            </td>
        </tr>
    }
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Bookcase/Views/Rate/UpdateRate.cshtml
@model Bookcase.ViewModels.RateVM
@{
    ViewBag.Title = "UpdateRate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edytuj Ocenę</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        

        <div class="form-group">
            @Html.LabelFor(model => model.BookId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>