Bookcase/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Profile;
using System.Web.UI.WebControls;
using BookcaseData.DAL;
using BookcaseData.EntityModels;
using BookcaseData.Repositories;
using Bookcase.ViewModels;
using PagedList;

namespace Bookcase.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;

        public BookController()
        {
            this._bookRepository = new BookRepository(new BookcaseContext());
        }

        

        // GET: Book
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {

            //ViewBag.BookID = id;
           
           
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "nameDescending" : "";
            ViewBag.WriterSortParm = sortOrder == "Writer" ? "writerDescending" : "Writer";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var allbooks = _bookRepository.GetAll();

            if (!string.IsNullOrEmpty(searchString))
            {
                allbooks = allbooks.Where(s => s.Title.ToLower().Contains(searchString) || s.Writer.ToLower().Contains(searchString));
                
            }

            switch (sortOrder)
            {
                case "nameDescending":
                   allbooks = allbooks.OrderByDescending(b => b.Title);
                    break;
                case "Writer":
                    allbooks = allbooks.OrderBy(b => b.Writer);
                    break;
                case "writerDescending":
                    allbooks = allbooks.OrderByDescending(b => b.Writer);
                    break;
                default:
                    allbooks = allbooks.OrderBy(b => b.Title);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            List<BookVM> booksVms = new List<BookVM>();
            foreach (var book in allbooks)
            {
                booksVms.Add(MapToVm(book));
            }

            return View(booksVms.ToPagedList(pageNumber, pageSize));
        }

        //GET
        public ActionResult AddBook()
        {
            return View("AddBook");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBook(BookVM bookVm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var book = new Book();
                    MapFromVm(bookVm, book);
                    _bookRepository.Add(book);
                    _bookRepository.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Wystąpił błąd zapisu, spróbuj ponownie");
            }
            return View(bookVm);
        }

        //GET
        public ActionResult UpdateBook(int id)
        {

            var book = _bookRepository.GetById(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(MapToVm(book));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateBook(BookVM bookVm)
        {
            if (bookVm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                var book = _bookRepository.GetById(bookVm.Id);
                MapFromVm(bookVm, book);
                _bookRepository.Update(book);

                try
                {
                    _bookRepository.Save();
                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Wystąpił błąd zapisu, spróbuj ponownie");
                }
            }
            return View(bookVm);
        }

        //GET
        public ActionResult DeleteBook(int id, bool? saveChanges = false)
        {
            if (saveChanges.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Błąd podczas usuwania, spróbuj ponownie";
            }
            var book = _bookRepository.GetById(id);
            
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(MapToVm(book));
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteBook(int id)
        {
            try
            {
                _bookRepository.Delete(id);
                _bookRepository.Save();
                
            }
            catch (RetryLimitExceededException)
            {
                return RedirectToAction("DeleteBook", new {id=id, saveChangesError=true});
            }
            return RedirectToAction("Index");
        }




        private static BookVM MapToVm(Book book)
        {
            return new BookVM
            {
                Title = book.Title,
                Writer = book.Writer,
                Genre = book.Genre,
                OwnerId = book.OwnerId,
                Id = book.Id
                
            };
        }

        private static void MapFromVm(BookVM vm, Book entity)
        {
            entity.Title = vm.Title;
            entity.Writer = vm.Writer;
            entity.Genre = vm.Genre;
            entity.OwnerId = vm.OwnerId;
            entity.Id = vm.Id;
        }

      
    }
}

Bookcase/Views/Book/AddBook.cshtml
@model Bookcase.ViewModels.BookVM
@{
    ViewBag.Title = "Add Book";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodaj książkę</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Writer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Writer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Writer, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.OwnerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cofnij do listy", "Index")
</div>

Bookcase/Views/Book/DeleteBook.cshtml
@model Bookcase.ViewModels.BookVM
@{
    ViewBag.Title = "DeleteBook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Usuń książkę</h2>

<h3>Na pewno?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Writer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Writer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróć do listy", "Index")
        </div>
    }
</div>

Bookcase/Views/Book/Index.cshtml
@model PagedList.IPagedList<Bookcase.ViewModels.BookVM>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Books";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Książki</h2>

@Html.ActionLink("Dodaj Książkę", "AddBook", "Book")
<br />
<br/>
@using (Html.BeginForm("Index", "Book", FormMethod.Get))
{
    <p>
        Szukaj: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Szukaj"/>
    </p>
}
<br/>
<table style="width: 50%" border-collapse: collapse>
    <tr>
        <th>
            @Html.ActionLink("Tytuł", "Index", new { SortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Autor", "Index", new { SortOrder = ViewBag.WriterSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Gatunek
        </th>
        <th></th>
        
    </tr>
    @foreach (var item in Model)
    {
        string selectedRow = "";
        if (item.Id == ViewBag.BookID)
        {
            selectedRow = "success";
        }
        <tr class="@selectedRow">
            <td>
                @Html.DisplayFor(modelItem=> item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Writer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
           
           
            <td>
               
                @Html.ActionLink("Select", "Index", new {id = item.Id})
                @Html.ActionLink("Edit", "UpdateBook", new {id = item.Id})
                @Html.ActionLink("Delete", "DeleteBook", new {id = item.Id})
            </td>
        </tr>
    }
</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))



@*@if (Model != null)
{
    <h3>Oceny wybranej książki</h3>
    <table class="table">
        <tr>
            <th></th>
            <th>Oceny</th>
        </tr>
        @foreach (var item in Model)
        {
            string selectedRow = "";
            if (item.Id == ViewBag.RateID)
            {
                selectedRow = "success";
            }
            <tr class="@selectedRow">
                <td>
                   
                </td>
                <td>
                    @item.Rates
                </td>
            </tr>
        }
    </table>
}*@

Bookcase/Views/Book/UpdateBook.cshtml
@model Bookcase.ViewModels.BookVM
@{
    ViewBag.Title = "UpdateBook";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edytuj książkę</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OwnerId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Writer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Writer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Writer, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>