Bookcase/Controllers/LendController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bookcase.ViewModels;
using BookcaseData.DAL;
using BookcaseData.EntityModels;
using BookcaseData.Repositories;
using PagedList;


namespace Bookcase.Controllers
{
    public class LendController : Controller
    {
        private readonly ILendRepository _lendRepository;
        private readonly IPersonRepository _personRepository;
        private readonly IBookRepository _bookRepository;

        public LendController()
        {
            this._lendRepository = new LendRepository(new BookcaseContext());
            this._personRepository = new PersonRepository(new BookcaseContext());
            this._bookRepository = new BookRepository(new BookcaseContext());
        }


        // GET: Lend
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSortParm = String.IsNullOrEmpty(sortOrder) ? "dateDescending" : "";
            ViewBag.NameSortParm = sortOrder == "Title" ? "titleDescending" : "Title";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var alllends = _lendRepository.GetAll();
            if (!string.IsNullOrEmpty(searchString))
            {
                alllends =
                    alllends.Where(
                        s =>
                            s.BookId.ToString().ToLower().Contains(searchString) ||
                            s.PersonId.ToString().ToLower().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "dateDescending":
                    alllends = alllends.OrderByDescending(b => b.Id);
                    break;
                case "Title":
                    alllends = alllends.OrderBy(b => b.BookId);
                    break;
                case "titleDescending":
                    alllends = alllends.OrderByDescending(b => b.BookId);
                    break;
                default:
                    alllends = alllends.OrderBy(b => b.Id);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            List<LendVM> lendVms = new List<LendVM>();
            foreach (var lend in alllends)
            {
                lendVms.Add(MapToVm(lend));
            }


            return View(lendVms.ToPagedList(pageNumber, pageSize));
        }

        private static LendVM MapToVm(Lend lend)
        {
            return new LendVM
            {
                BorrowDateTime = lend.BorrowDateTime,
                ReturnDateTime = lend.ReturnDateTime,
                BookId = lend.BookId,
                PersonId = lend.PersonId,
                Id = lend.Id,
                BookName = lend.Book.Title,
                PersonName = lend.Person.Fullname
            };
        }

        private static void MapFromVm(LendVM vm, Lend entity)
        {
            entity.BorrowDateTime = vm.BorrowDateTime;
            entity.ReturnDateTime = vm.ReturnDateTime;
            entity.BookId = vm.BookId;
            entity.PersonId = vm.PersonId;
            entity.Id = vm.Id;
        }



        //GET
        public ActionResult AddLend()
        {
            var lendVm = new LendVM();
            SetUsersSelectList(lendVm);
            SetBooksSelectList(lendVm);


            return View("AddLend", lendVm);
        }

        private void SetUsersSelectList(LendVM vm)
        {
            vm.UsersSelectList =
                _personRepository.GetAll()
                    .Select(x => new SelectListItem() { Text = x.Fullname, Value = x.Id.ToString() })
                    .ToList();
        }

        private void SetBooksSelectList(LendVM vm)
        {
            vm.BooksSelectList =
                _bookRepository.GetAll()
                    .Select(x => new SelectListItem() { Text = x.Title, Value = x.Id.ToString() })
                    .ToList();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddLend(LendVM lendVm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var lend = new Lend();
                    MapFromVm(lendVm, lend);
                    _lendRepository.Add(lend);
                    _lendRepository.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Wystąpił błąd zapisu, spróbuj ponownie");
            }

            return View(lendVm);
        }

        [HttpPost]
        public JsonResult PostPerson(PersonVM personVm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var person = new Person();
                    MapFromVm(personVm, person);
                    _personRepository.Add(person);
                    _personRepository.Save();
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Wystąpił błąd zapisu, spróbuj ponownie");
            }


            return Json(personVm);
        }
        private static void MapFromVm(PersonVM vm, Person entity)
        {
            entity.Name = vm.Name;
            entity.LastName = vm.LastName;
            entity.Id = vm.Id;
        }


        //GET
        public ActionResult UpdateLend(int id)
        {

            var lend = _lendRepository.GetById(id);
            if (lend == null)
            {
                return HttpNotFound();
            }
            return View(MapToVm(lend));


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateLend(LendVM lendVm)
        {
            if (lendVm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                var lend = _lendRepository.GetById(lendVm.Id);
                MapFromVm(lendVm, lend);
                _lendRepository.Update(lend);

                try
                {
                    _lendRepository.Save();
                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Wystąpił błąd zapisu, spróbuj ponownie");
                }
            }
            return View(lendVm);
        }

        //GET
        public ActionResult DeleteLend(int id, bool? saveChanges = false)
        {
            if (saveChanges.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Błąd podczas usuwania, spróbuj ponownie";
            }
            var lend = _lendRepository.GetById(id);

            if (lend == null)
            {
                return HttpNotFound();
            }
            return View(MapToVm(lend));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteLend(int id)
        {
            try
            {
                _lendRepository.Delete(id);
                _lendRepository.Save();

            }
            catch (RetryLimitExceededException)
            {
                return RedirectToAction("DeleteLend", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }





    }
}

Bookcase/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bookcase.ViewModels;
using BookcaseData.DAL;
using BookcaseData.EntityModels;
using BookcaseData.Repositories;
using PagedList;

namespace Bookcase.Controllers
{
    public class PersonController : Controller
    {
        private readonly IPersonRepository _personRepository;

        public PersonController()
        {
            this._personRepository = new PersonRepository(new BookcaseContext());
        }


        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "nameDescending" : "";
            ViewBag.WriterSortParm = sortOrder == "LastName" ? "lastNameDescending" : "LastName";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var allpersons = _personRepository.GetAll();

            if (!string.IsNullOrEmpty(searchString))
            {
                allpersons = allpersons.Where(s => s.Name.ToLower().Contains(searchString) || s.LastName.ToLower().Contains(searchString));

            }

            switch (sortOrder)
            {
                case "nameDescending":
                    allpersons = allpersons.OrderByDescending(b => b.Name);
                    break;
                case "LastName":
                    allpersons = allpersons.OrderBy(b => b.LastName);
                    break;
                case "lastNameDescending":
                    allpersons = allpersons.OrderByDescending(b => b.LastName);
                    break;
                default:
                    allpersons = allpersons.OrderBy(b => b.Name);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            List<PersonVM> peoplesVms = new List<PersonVM>();
            foreach (var person in allpersons)
            {
                peoplesVms.Add(MapToVm(person));
            }

            return View(peoplesVms.ToPagedList(pageNumber, pageSize));
        }

        //GET
        [HttpGet]
        public ActionResult AddPerson(string returnAction, string returnController)
        {
            ViewBag.ReturnUrl = returnAction;
            ViewBag.ReturnController = returnController;
            return View("AddPerson");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPerson(PersonVM personVm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var person = new Person();
                    MapFromVm(personVm, person);
                    _personRepository.Add(person);
                    _personRepository.Save();
                    if (!string.IsNullOrEmpty(ViewBag.ReturnUrl))
                    {
                        return RedirectToAction(ViewBag.ReturnUrl, ViewBag.ReturnController);
                    }

                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Wystąpił błąd zapisu, spróbuj ponownie");
            }
            return View(personVm);
        }

        //GET
        public ActionResult UpdatePerson(int id)
        {

            var person = _personRepository.GetById(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(MapToVm(person));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdatePerson(PersonVM personVm)
        {
            if (personVm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                var book = _personRepository.GetById(personVm.Id);
                MapFromVm(personVm, book);
                _personRepository.Update(book);

                try
                {
                    _personRepository.Save();
                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Wystąpił błąd zapisu, spróbuj ponownie");
                }
            }
            return View(personVm);
        }

        //GET
        public ActionResult DeletePerson(int id, bool? saveChanges = false)
        {
            if (saveChanges.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Błąd podczas usuwania, spróbuj ponownie";
            }
            var person = _personRepository.GetById(id);

            if (person == null)
            {
                return HttpNotFound();
            }
            return View(MapToVm(person));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePerson(int id)
        {
            try
            {
                _personRepository.Delete(id);
                _personRepository.Save();

            }
            catch (RetryLimitExceededException)
            {
                return RedirectToAction("DeletePerson", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult GetPersons()
        {
            var allPersons = _personRepository.GetAll();

            var list =
                new List<dynamic>() { new { Value = -1, Text = "--Wybierz--" } }.Union(
                    allPersons.Select(x => new { Value = x.Id, Text = x.Fullname }));

            return Json(list, JsonRequestBehavior.AllowGet);
        }


        private static PersonVM MapToVm(Person person)
        {
            return new PersonVM()
            {
                Name = person.Name,
                LastName = person.LastName,
                Id = person.Id

            };
        }

        private static void MapFromVm(PersonVM vm, Person entity)
        {
            entity.Name = vm.Name;
            entity.LastName = vm.LastName;
            entity.Id = vm.Id;
        }
    }
}

Bookcase/Views/Lend/AddLend.cshtml
@model Bookcase.ViewModels.LendVM
@{
    ViewBag.Title = "Add Lend";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodaj wypoożyczenie</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BorrowDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BorrowDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BorrowDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReturnDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.BookId, Model.BooksSelectList, "Wybierz", new { required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.PersonId, Model.UsersSelectList, "Wybierz", new { required = "required",id="userDdl" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>

}
<br />
<div>


    <div class="container">
        <!-- Trigger the modal with a button -->
        <button type="button" class="btn btn-default"  id="myBtn">Dodaj użytkownika</button>

        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Dodaj użytkownika</h4>
                    </div>
                    <div class="modal-body">

                        <div id="PersonDiv">
                        </div>

                        <form metod="post" name="formularz">

                            <p>Imię</p>
                            <input type="text" id="imie" name="name" />
                            <p></p>
                            <p>Nazwisko</p>
                            <input type="text" id="nazwisko" name="lastName" />

                            <br /><br />
                            <input type="button" value="Zapisz" id="przycisk" name="przycisk" />

                        </form>

                        <script type="text/javascript">

                            $(document).ready(function () {
                                var modalElement = $('#myModal');
                                $("#myBtn").click(function() {
                                    modalElement.modal('show');
                                });

                                $("#przycisk").click(function () {
                                    $.ajax({
                                        url: '@Url.Action("PostPerson")',
                                        cache: false,
                                        method: "POST",
                                        dataType: "JSON",
                                        data: $("form[name=formularz]").serialize(),
                                        success: function (data) {
                                            $("#PersonDiv").append(" Użytkownik" + data.Name + " " + data.LastName + " został odany" + "</br>");
                                            modalElement.modal('hide');
                                            promise.success(data);
                                            $.getJSON('@Url.Action("GetPersons","Person")',
                                                function(result) {
                                                    var userDdl = $("#userDdl");
                                                    userDdl.empty();

                                                    $.each(result, function() {
                                                        $(document.createElement('option'))
                                                            .attr('value',this.Value)
                                                            .text(this.Text)
                                                            .appendTo(userDdl);
                                                    });
                                                });
                                        }
                                    });

                                });
                            });
                        </script>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>

    </div>
    @*@Html.ActionLink("Dodaj Użytkownika", "AddPerson", "Person", new { returnAction = "AddLend", returnController="Lend"},null)*@
</div>
<br />
<div>
    @Html.ActionLink("Cofnij do listy", "Index")
</div>

Bookcase/Views/Lend/DeleteLend.cshtml
@model Bookcase.ViewModels.LendVM
@{
    ViewBag.Title = "DeleteLend";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Usuń książkę</h2>

<h3>Na pewno?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BorrowDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BorrowDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BookName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PersonName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> |
            @Html.ActionLink("Wróć do listy", "Index")
        </div>
    }
</div>

Bookcase/Views/Lend/Index.cshtml
@model PagedList.IPagedList<Bookcase.ViewModels.LendVM>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Lends";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Wypożyczenia</h2>

@Html.ActionLink("Dodaj wypożyczenie", "AddLend", "Lend")
<br />
<br />
@using (Html.BeginForm("Index", "Lend", FormMethod.Get))
{
    <p>
        Szukaj: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Szukaj" />
    </p>
}
<br />
<table style="width: 50%" border-collapse collapse>
    <tr>
        <th>
            @Html.ActionLink("ID", "Index", new { SortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Wypożyczający", "Index", new {SortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter})
        </th>
        <th>
            Tytuł książki
        </th>
        <th>
            Data Wypożyczenia
        </th>
        <th>
            Data Oddania
        </th>
        <th></th>


    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PersonName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookName)
            </td>
            <td>
                @item.BorrowDateTime.ToShortDateString()
            </td>
            <td>
                @item.ReturnDateTime.ToShortDateString()
            </td>



            <td>
                @Html.ActionLink("Edit", "UpdateLend", new {id = item.Id})
                @Html.ActionLink("Delete", "DeleteLend", new {id = item.Id})
            </td>
        </tr>
    }
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Bookcase/Views/Lend/UpdateLend.cshtml
@model Bookcase.ViewModels.LendVM
@{
    ViewBag.Title = "UpdateLend";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edytuj Wypożyczenia</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">


        <div class="form-group">
            @Html.LabelFor(model => model.BorrowDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BorrowDateTime, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.BorrowDateTime, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReturnDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReturnDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReturnDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PersonId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do listy", "Index")
</div>